name: build

on:
  push:
    tags:
      - v*
    branches:
      - master

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up maven and java environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Perform the maven build
        run: mvn -B clean package --file app/pom.xml
      - uses: actions/upload-artifact@v3
        with:
          name: todolist-migrator-build-artifacts
          path: app/target/*.jar
  image-build-push:
    name: Docker image build and push to registry
    needs: maven-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download a maven build artifacts
        uses: actions/download-artifact@v3
        with:
          name: todolist-migrator-build-artifacts
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and push Docker image
        with:
          image: anadinema/todolist-migrator
          labels: |
            maintainer=anadinema,
            org=dev.anadinema,
            mail=anadi.nema@outlook.com
          registry: docker.io
          dockerfile: app/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
